version: '3'

networks:
    internal:
        external: true

services:
    api:
        container_name: api
        build:
            context: .
            dockerfile: ./microservices-docker/api.Dockerfile
        environment:
            PORT: 3000
            RMQ_HOST: cart-rabbitmq-3.8.3
            RMQ_USERNAME: guest
            RMQ_PASSWORD: guest
            RMQ_PORT: 5672
            RMQ_VHOST: ''
            RMQ_QUEUE_DURABLE_CONFIG: 'true'
            DATABASE_URL: 'mysql://root:main@cart-mysql-8.0:3306/cart'
            JWT_TOKEN_EXPIRATION_TIME: 3600
            CART_JWT_SECRET_PHRASE: a34fe21f235ecb49a05d25eb9b612cc3f57911eda8ddd11f9d09856a26dcb07f
        ports:
            - 3000:3000
        networks:
            - internal

    cart:
        container_name: cart
        build:
            context: .
            dockerfile: ./microservices-docker/cart.Dockerfile
        environment:
            RMQ_HOST: cart-rabbitmq-3.8.3
            RMQ_USERNAME: guest
            RMQ_PASSWORD: guest
            RMQ_PORT: 5672
            RMQ_VHOST: ''
            RMQ_QUEUE_DURABLE_CONFIG: 'true'
            DB_HOST: cart-mysql-8.0
            DB_PORT: 3306
            DB_USER: root
            DB_PASSWORD: main
            DB_NAME: cart
            DATABASE_URL: 'mysql://root:main@cart-mysql-8.0:3306/cart'
            JWT_TOKEN_EXPIRATION_TIME: 3600
            CART_JWT_SECRET_PHRASE: a34fe21f235ecb49a05d25eb9b612cc3f57911eda8ddd11f9d09856a26dcb07f
        networks:
            - internal

    checkout:
        container_name: checkout
        build:
            context: .
            dockerfile: ./microservices-docker/checkout.Dockerfile
        environment:
            RMQ_HOST: cart-rabbitmq-3.8.3
            RMQ_USERNAME: guest
            RMQ_PASSWORD: guest
            RMQ_PORT: 5672
            RMQ_VHOST: ''
            RMQ_QUEUE_DURABLE_CONFIG: 'true'
            DB_HOST: cart-mysql-8.0
            DB_PORT: 3306
            DB_USER: root
            DB_PASSWORD: main
            DB_NAME: cart
            DATABASE_URL: 'mysql://root:main@cart-mysql-8.0:3306/cart'
            JWT_TOKEN_EXPIRATION_TIME: 3600
            CART_JWT_SECRET_PHRASE: a34fe21f235ecb49a05d25eb9b612cc3f57911eda8ddd11f9d09856a26dcb07f
            # MP_HOST: "https://api.mercadopago.com"
            # MP_ENDPOINT: "/checkout/preferences"
            # MP_ACCESS_TOKEN: ""
            # SUCCESS_BACK_URL: ""
            # PENDING_BACK_URL: ""
            # FAILURE_BACK_URL: ""
        networks:
            - internal

    product:
        container_name: product
        build:
            context: .
            dockerfile: ./microservices-docker/product.Dockerfile
        environment:
            RMQ_HOST: cart-rabbitmq-3.8.3
            RMQ_USERNAME: guest
            RMQ_PASSWORD: guest
            RMQ_PORT: 5672
            RMQ_VHOST: ''
            RMQ_QUEUE_DURABLE_CONFIG: 'true'
            DB_HOST: cart-mysql-8.0
            DB_PORT: 3306
            DB_USER: root
            DB_PASSWORD: main
            DB_NAME: cart
            DATABASE_URL: 'mysql://root:main@cart-mysql-8.0:3306/cart'
            JWT_TOKEN_EXPIRATION_TIME: 3600
            CART_JWT_SECRET_PHRASE: a34fe21f235ecb49a05d25eb9b612cc3f57911eda8ddd11f9d09856a26dcb07f
        networks:
            - internal

    product-price:
        container_name: product-price
        build:
            context: .
            dockerfile: ./microservices-docker/product-price.Dockerfile
        environment:
            RMQ_HOST: cart-rabbitmq-3.8.3
            RMQ_USERNAME: guest
            RMQ_PASSWORD: guest
            RMQ_PORT: 5672
            RMQ_VHOST: ''
            RMQ_QUEUE_DURABLE_CONFIG: 'true'
            DB_HOST: cart-mysql-8.0
            DB_PORT: 3306
            DB_USER: root
            DB_PASSWORD: main
            DB_NAME: cart
            DATABASE_URL: 'mysql://root:main@cart-mysql-8.0:3306/cart'
            JWT_TOKEN_EXPIRATION_TIME: 3600
            CART_JWT_SECRET_PHRASE: a34fe21f235ecb49a05d25eb9b612cc3f57911eda8ddd11f9d09856a26dcb07f
        networks:
            - internal

    user:
        container_name: user
        build:
            context: .
            dockerfile: ./microservices-docker/user.Dockerfile
        environment:
            RMQ_HOST: cart-rabbitmq-3.8.3
            RMQ_USERNAME: guest
            RMQ_PASSWORD: guest
            RMQ_PORT: 5672
            RMQ_VHOST: ''
            RMQ_QUEUE_DURABLE_CONFIG: 'true'
            DB_HOST: cart-mysql-8.0
            DB_PORT: 3306
            DB_USER: root
            DB_PASSWORD: main
            DB_NAME: cart
            DATABASE_URL: 'mysql://root:main@cart-mysql-8.0:3306/cart'
            JWT_TOKEN_EXPIRATION_TIME: 3600
            CART_JWT_SECRET_PHRASE: a34fe21f235ecb49a05d25eb9b612cc3f57911eda8ddd11f9d09856a26dcb07f
        networks:
            - internal
