version: '3'

networks:
    internal:
        external: true

services:
    meli-api:
        container_name: meli-api
        build:
            context: .
            dockerfile: ./melicontrol-microservices-docker/meli-api.Dockerfile
        environment:
            PORT: 3000
            RMQ_HOST: melicontrol-rabbitmq-3.8.3
            RMQ_USERNAME: guest
            RMQ_PASSWORD: guest
            RMQ_PORT: 5672
            RMQ_VHOST: ''
            RMQ_QUEUE_DURABLE_CONFIG: 'true'
            DATABASE_URL: 'mysql://root:main@melicontrol-mysql-8.0:3306/melicontrol'
            JWT_TOKEN_EXPIRATION_TIME: 3600
            MELI_JWT_SECRET_PHRASE: a34fe21f235ecb49a05d25eb9b612cc3f57911eda8ddd11f9d09856a26dcb07f
        ports:
            - 3000:3000
        networks:
            - internal

    meli-cart:
        container_name: meli-cart
        build:
            context: .
            dockerfile: ./melicontrol-microservices-docker/meli-cart.Dockerfile
        environment:
            RMQ_HOST: melicontrol-rabbitmq-3.8.3
            RMQ_USERNAME: guest
            RMQ_PASSWORD: guest
            RMQ_PORT: 5672
            RMQ_VHOST: ''
            RMQ_QUEUE_DURABLE_CONFIG: 'true'
            DB_HOST: melicontrol-mysql-8.0
            DB_PORT: 3306
            DB_USER: root
            DB_PASSWORD: main
            DB_NAME: melicontrol
            DATABASE_URL: 'mysql://root:main@melicontrol-mysql-8.0:3306/melicontrol'
            JWT_TOKEN_EXPIRATION_TIME: 3600
            MELI_JWT_SECRET_PHRASE: a34fe21f235ecb49a05d25eb9b612cc3f57911eda8ddd11f9d09856a26dcb07f
        networks:
            - internal

    meli-checkout:
        container_name: meli-checkout
        build:
            context: .
            dockerfile: ./melicontrol-microservices-docker/meli-checkout.Dockerfile
        environment:
            RMQ_HOST: melicontrol-rabbitmq-3.8.3
            RMQ_USERNAME: guest
            RMQ_PASSWORD: guest
            RMQ_PORT: 5672
            RMQ_VHOST: ''
            RMQ_QUEUE_DURABLE_CONFIG: 'true'
            DB_HOST: melicontrol-mysql-8.0
            DB_PORT: 3306
            DB_USER: root
            DB_PASSWORD: main
            DB_NAME: melicontrol
            DATABASE_URL: 'mysql://root:main@melicontrol-mysql-8.0:3306/melicontrol'
            JWT_TOKEN_EXPIRATION_TIME: 3600
            MELI_JWT_SECRET_PHRASE: a34fe21f235ecb49a05d25eb9b612cc3f57911eda8ddd11f9d09856a26dcb07f
            # MP_HOST: "https://api.mercadopago.com"
            # MP_ENDPOINT: "/checkout/preferences"
            # MP_ACCESS_TOKEN: ""
            # SUCCESS_BACK_URL: "https://dev.melicontrol.com.br/MercadoPago/SuccessPayment/Plan"
            # PENDING_BACK_URL: "https://dev.melicontrol.com.br/MercadoPago/PendingPayment/Plan"
            # FAILURE_BACK_URL: "https://dev.melicontrol.com.br/MercadoPago/FailurePayment/Plan"
        networks:
            - internal

    meli-product:
        container_name: meli-product
        build:
            context: .
            dockerfile: ./melicontrol-microservices-docker/meli-product.Dockerfile
        environment:
            RMQ_HOST: melicontrol-rabbitmq-3.8.3
            RMQ_USERNAME: guest
            RMQ_PASSWORD: guest
            RMQ_PORT: 5672
            RMQ_VHOST: ''
            RMQ_QUEUE_DURABLE_CONFIG: 'true'
            DB_HOST: melicontrol-mysql-8.0
            DB_PORT: 3306
            DB_USER: root
            DB_PASSWORD: main
            DB_NAME: melicontrol
            DATABASE_URL: 'mysql://root:main@melicontrol-mysql-8.0:3306/melicontrol'
            JWT_TOKEN_EXPIRATION_TIME: 3600
            MELI_JWT_SECRET_PHRASE: a34fe21f235ecb49a05d25eb9b612cc3f57911eda8ddd11f9d09856a26dcb07f
        networks:
            - internal

    meli-product-price:
        container_name: meli-product-price
        build:
            context: .
            dockerfile: ./melicontrol-microservices-docker/meli-product-price.Dockerfile
        environment:
            RMQ_HOST: melicontrol-rabbitmq-3.8.3
            RMQ_USERNAME: guest
            RMQ_PASSWORD: guest
            RMQ_PORT: 5672
            RMQ_VHOST: ''
            RMQ_QUEUE_DURABLE_CONFIG: 'true'
            DB_HOST: melicontrol-mysql-8.0
            DB_PORT: 3306
            DB_USER: root
            DB_PASSWORD: main
            DB_NAME: melicontrol
            DATABASE_URL: 'mysql://root:main@melicontrol-mysql-8.0:3306/melicontrol'
            JWT_TOKEN_EXPIRATION_TIME: 3600
            MELI_JWT_SECRET_PHRASE: a34fe21f235ecb49a05d25eb9b612cc3f57911eda8ddd11f9d09856a26dcb07f
        networks:
            - internal

    meli-user:
        container_name: meli-user
        build:
            context: .
            dockerfile: ./melicontrol-microservices-docker/meli-user.Dockerfile
        environment:
            RMQ_HOST: melicontrol-rabbitmq-3.8.3
            RMQ_USERNAME: guest
            RMQ_PASSWORD: guest
            RMQ_PORT: 5672
            RMQ_VHOST: ''
            RMQ_QUEUE_DURABLE_CONFIG: 'true'
            DB_HOST: melicontrol-mysql-8.0
            DB_PORT: 3306
            DB_USER: root
            DB_PASSWORD: main
            DB_NAME: melicontrol
            DATABASE_URL: 'mysql://root:main@melicontrol-mysql-8.0:3306/melicontrol'
            JWT_TOKEN_EXPIRATION_TIME: 3600
            MELI_JWT_SECRET_PHRASE: a34fe21f235ecb49a05d25eb9b612cc3f57911eda8ddd11f9d09856a26dcb07f
        networks:
            - internal