version: '3'

networks:
    internal:
        external: true

services:
    meli-api:
        container_name: meli-api
        build:
            context: .
            dockerfile: ./melicontrol-microservices-docker/meli-api.Dockerfile
        environment:
            PORT: 3000
            RMQ_HOST: melicontrol-rabbitmq-3.8.3
            RMQ_USERNAME: main
            RMQ_PASSWORD: main
            RMQ_PORT: 5672
            RMQ_VHOST: ''
            RMQ_QUEUE_DURABLE_CONFIG: 'true'
            DATABASE_URL: 'mysql://root:main@melicontrol-mysql-8.0:3306/melicontrol'
            JWT_TOKEN_EXPIRATION_TIME: 3600
            JWT_SECRET_PHRASE: asdaasdasdasdasdasdasdasdasdasdasdasdasdasdasdasd
        ports:
            - 3000:3000
        networks:
            - internal

    meli-cart:
        container_name: meli-cart
        build:
            context: .
            dockerfile: ./melicontrol-microservices-docker/meli-cart.Dockerfile
        environment:
            RMQ_HOST: melicontrol-rabbitmq-3.8.3
            RMQ_USERNAME: main
            RMQ_PASSWORD: main
            RMQ_PORT: 5672
            RMQ_VHOST: ''
            RMQ_QUEUE_DURABLE_CONFIG: 'true'
            DB_HOST: melicontrol-mysql-8.0
            DB_PORT: 3306
            DB_USER: root
            DB_PASSWORD: main
            DB_NAME: melicontrol
            DATABASE_URL: 'mysql://root:main@melicontrol-mysql-8.0:3306/melicontrol'
        networks:
            - internal
