version: '3'

networks:
    internal:
        external: true

services:
    meli-notification:
        container_name: meli-notification
        build: .
        environment:
            PORT: 3200
            RMQ_HOST: mcrabbitmq04.eastus.cloudapp.azure.com
            RMQ_USERNAME: azure
            RMQ_PASSWORD: MLFacil2017
            RMQ_PORT: 5672
            RMQ_VHOST: ''
            RMQ_QUEUE_DURABLE_CONFIG: 'true'
        volumes:
            - .:/usr/src/app
        ports:
            - 3200:3200
        networks:
            - internal

    # meli-notification:
    #   image: melicontainerregistry.azurecr.io/melicontrolmicroservices-meli-notification:latest
    #   container_name: meli-notification
    #   environment:
    #     PORT: 3200
    #     RMQ_HOST: mcrabbitmq04.eastus.cloudapp.azure.com
    #     RMQ_USERNAME: azure
    #     RMQ_PASSWORD: MLFacil2017
    #     RMQ_PORT: 5672
    #     RMQ_VHOST: ''
    #     RMQ_QUEUE_DURABLE_CONFIG: "true"
    #     LOG_SYNC: 1
    #   ports:
    #     - 3200:3200
    #   networks:
    #     - internal
