version: '3.7'

networks:
  internal:
    external: true
  cart-network:
    driver: bridge

services:
  mysql:
    container_name: cart-mysql-8.0
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    environment:
      - MYSQL_DATABASE=cart
      - MYSQL_ROOT_PASSWORD=main
    ports:
      - '3306:3306'
    volumes:
      - ./services/mysql/data:/var/lib/mysql
      - ./services/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - cart-network
      - internal

  rabbitmq:
    container_name: cart-rabbitmq-3.8.3
    image: rabbitmq:3.8-management
    volumes:
      - ./services/rabbitmq/data:/var/lib/rabbitmq/
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - cart-network
      - internal
