GET http://localhost:3000/cart/1
Content-Type: application/json

###
POST http://localhost:3000/cart
Content-Type: application/json

{
	"user_id": 2,
	"title": "cart-teste-2",
	"status": true,
	"default": false
}

###
PUT http://localhost:8888/cart/22
Content-Type: application/json

{
	"title": "cart-teste-2",
	"status": true,
	"default": false
}

###
POST http://localhost:8888/cart/addItem
Content-Type: application/json

{
	"cart_id": 5,
	"product_id": 1,
	"product_price_id": 1,
	"months": 3,
	"price": 100,
	"status": true
}
###
DELETE http://localhost:8888/cart/deleteItem/19
Content-Type: application/json
